import type { Metadata } from "next";
import { IBM_Plex_Mono as IBMPlexMono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const ibmPlexMono = IBMPlexMono({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700"],
});

export const metadata: Metadata = {
  title: "Portfolio - Thishan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexMono.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
